import type { Metadata } from "next";
import "./globals.css";
  import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Blabolizer1612",
  description: "Generated by lots of late mornings and early nights",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}
        </ClientLayout>

      </body>
    </html>
  );
}